services:
  ubuntu:
    image: lscr.io/linuxserver/rdesktop:ubuntu-mate
    container_name: rdesktop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - /home/rafael/:/config/out/ #optional
    ports:
      - 3392:3389
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped

    # default user/password: abc
